#scp -pr . root@103.124.93.29:/root/
version: '3.7'

services:

  mysql8-container:
    container_name: mysql8-webcoco-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KHANH2005t
      MYSQL_DATABASE: WebCoCo
    ports:
      - 3309:3306
    volumes:
      - ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - webcoco-network

  redis-container:
    image: docker.io/redis:latest
    container_name: redis-webcoco-container
    restart: always
    ports:
      - "6380:6379" # Port mapping for Redis
#    command: [ "redis-server", "--requirepass", "KHANH2005t", "--user", "default" ]
    volumes:
      - ./redis-data:/data # Mount a volume for Redis data persistence
    networks:
      - webcoco-network

networks:
  webcoco-network:
    driver: bridge


#  shopapp-spring-container:
#    container_name: shopapp-spring-container
#    build:
#      context: .
#      dockerfile: DockerfileJavaSpring
#    ports:
#      - 8099:8091
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/ShopApp?serverTimezone=UTC&allowPublicKeyRetrieval=true
#      MYSQL_ROOT_PASSWORD: KHANH2005t
#      REDIS_HOST: redis-container
#      REDIS_PORT: 6379
#
#    depends_on:
#      - mysql8-container
#    networks:
#      - shopapp-network



#  docker-compose up -d

#docker-compose -f ./deployment.yaml down

#docker-compose -f ./deployment.yaml rm -s -f mysql8-container
#docker-compose -f ./deployment.yaml up -d mysql8-container

#docker-compose -f ./deployment.yaml rm -s -f phpmyadmin8-container
#docker-compose -f ./deployment.yaml up -d phpmyadmin8-container


#docker-compose -f ./deployment.yaml rm -s -f shopapp-spring-container
#docker-compose -f ./deployment.yaml up -d shopapp-spring-container
#docker logs shopapp-spring-container

#docker-compose -f ./deployment.yaml rm -s -f redis-container
#docker-compose -f ./deployment.yaml up -d redis-container




